nodeLinker: node-modules

npmRegistryServer: "https://sonatype.jodibooks.com/repository/yarn-npm-group/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
