export const content = {
    '404Header': '404',
    '404Message': 'The page you\'re looking for does not exist (anymore).',
    '404Title': 'Page not found',
    AllRightsReserved: 'All rights reserved.',
    Back: 'Back',
    BacktoPortfolio: 'Back to portfolio',
    Banner: 'Banner',
    Blog: 'Blog',
    Business: 'Business name',
    Clear: 'Clear',
    CompanyAddress: 'Address',
    CompanyInfo: 'Company Info',
    Compute: 'Compute',
    Conditions: 'Conditions',
    Copied: 'Copied',
    Copy: 'Copy',
    Email: 'Email',
    EmailError: 'Error!',
    EmailErrorBody: 'Thank you for your interest. Something went wrong sending your message. Please try again or use another channel to contact me.',
    EmailErrorMessage: 'Enter a valid email address',
    EmailSending: 'Sending',
    EmailSendingBody: 'Sending the email...',
    Filter: 'Filter',
    FilterTags: 'Select tags to show',
    Hosting: 'Hosting',
    InterestedIn: 'I\'m interested in:',
    Loading: 'Loading...',
    MailSendFailed: 'Something went wrong, please try again or email me directly at ',
    MailSendSuccess: 'Thank you for sending this message. I\'ll get back to you as soon as I can.',
    More: 'More',
    Name: 'Name',
    NameErrorMessage: 'Please enter a name',
    NextPost: 'Next post: ',
    NoOptionsSelect: 'No further tags available',
    Ok: 'Ok',
    PreviousPost: 'Previous post: ',
    PrivacyStatement: 'Privacy Statement',
    SendEmail: 'Or send me an email',
    SendEmailDone: 'Thank you for your enquiry',
    ShowAll: 'Show all',
    Submit: 'Submit',
    TermsOfService: 'Terms of service',
    TextBox: 'Questions / other',
    TryAgain: 'Try again',
    Websites: 'Websites',
    WebsiteDesign: 'Website design',
    WebsiteHosting: 'Website hosting',
    WebsiteUpdates: 'Website updates',
    WebshopSetup: 'Webshop setup',
    WebshopHosting: 'Webshop hosting',
    WebHosting: 'Website/webshop hosting',
    WelcomeTo: 'Welcome to'
};
