export const content = {
    '404Header': '404',
    '404Message': 'The page you\'re looking for does not exist (anymore).',
    '404Title': 'Page not found',
    AllRightsReserved: 'All rights reserved.',
    Back: 'Back',
    BacktoPortfolio: 'Back to portfolio',
    Banner: 'Banner',
    Blog: 'Blog',
    Business: 'Business name',
    CompanyAddress: 'Address',
    CompanyInfo: 'Company Info',
    ComputeHosting: 'Compute',
    Conditions: 'Conditions',
    Copy: 'Copy',
    Email: 'Email',
    EmailErrorMessage: 'Enter a valid email address',
    Filter: 'Filter',
    FilterTags: 'Select tags to show',
    HowtoDisclaimer: 'How-to written and screenshots taken on',
    InterestedIn: 'I\'m interested in:',
    Loading: 'Loading...',
    MailSendFailed: 'Something went wrong, please try again or email me directly at ',
    MailSendSuccess: 'Thank you for sending this message. I\'ll get back to you as soon as I can.',
    More: 'More',
    Name: 'Name',
    NameErrorMessage: 'Please enter a name',
    NextPost: 'Next post: ',
    NoOptionsSelect: 'No further tags available',
    Ok: 'Ok',
    PreviousPost: 'Previous post: ',
    PrivacyStatement: 'Privacy Statement',
    SendEmail: 'Or send me an email',
    SendEmailDone: 'Thank you for your enquiry',
    ShowAll: 'Show all',
    Submit: 'Submit',
    TermsOfService: 'Terms of service',
    TextBox: 'Questions / other',
    TryAgain: 'Try again',
    WebDesign: 'Website design',
    WebHosting: 'Website hosting',
    WelcomeTo: 'Welcome to'
};