export const content = {
    About: 'About',
    AllRightsReserved: 'All rights reserved.',
    Back: 'Back',
    Backto: 'Back to overview',
    BacktoPortfolio: 'Back to portfolio',
    Banner: 'Banner',
    Blog: 'Blog',
    Business: 'Business name',
    Contact: 'Contact',
    Continue: 'Continue',
    Email: 'Email',
    EmailErrorMessage: 'Enter a valid email address',
    Filter: 'Filter',
    FilterTags: 'Select tags to show',
    Home: 'Home',
    Howto: 'How-to',
    Info: 'Info',
    InterestedIn: 'I\'m interested in:',
    Loading: 'Loading...',
    MailSendFailed: 'Something went wrong, please try again or email me directly at ',
    MailSendSuccess: 'Thank you for sending this message. I\'ll get back to you as soon as I can.',
    Name: 'Name',
    NameErrorMessage: 'Please enter a name',
    NoOptionsSelect: 'No further tags available',
    Ok: 'Ok',
    Portfolio: 'Portfolio',
    Pricing: 'Pricing',
    PricingDesign: 'Design',
    Recommended: 'Recommended',
    SelectedTags: 'Selected tags',
    SendEmail: 'Send me an email',
    SendEmailDone: 'Thank you for your enquiry',
    Services: 'Services',
    ShowAll: 'Show all',
    ShowModal: 'Show more',
    ShowModalMessage: 'This website does not work properly in your current browser.',
    Submit: 'Submit',
    TextBox: 'Questions / other',
    TryAgain: 'Try again',
    UnsupportedContinue: 'Press continue to view this site anyway.',
    UnsupportedMessage: 'This website does not work properly in your current browser. Use one of the browser below for the best experience.',
    UnsupportedTitle: 'Browser not supported',
    WebDesign: 'Website design',
    WebHosting: 'Website hosting'
};
export const metaData = {
    AuthorName: `Joep van de Laarschot`,
    BusinessName: 'Joeplaa',
    FirstName: 'Joep',
    LastName: 'van de Laarschot',
    HomeDescription: 'Who is Joep and what is Joeplaa?',
    HomeImage: '/images/banner-www-com-white.png',
    HomeTitle: 'Welcome to',
    HomeSubtitle: 'Website design | Website hosting',
    HowtoDescription: 'How-to\'s and tutorials on subjects: Ubuntu, file-sharing, virtual machines and website hosting.',
    HowtoImage: '/images/banner-www-howto-white.png',
    HowtoTitle: 'How-to',
    LandingDescription: 'Welcome on joeplaa.com. Click on the links to explore further.',
    LandingTitle: 'Landing',
    PageTitle: ' | joeplaa.com',
    PortfolioDescription: 'Examples of my work and skills in front-end development. If you want a website, let me know!',
    PortfolioImage: '/images/banner-www-websites-white.png',
    PortfolioTitle: 'Portfolio',
    PricingDescription: 'If you want a website, here\'s what it costs.',
    PricingTitle: 'Pricing',
    SiteDescription: 'Helping people create their digital home.',
    SiteImage: `/images/banner-www-default-white.png`,
    SiteLanguage: `en-US`,
    SiteLocale: `en_us`,
    SiteName: 'joeplaa.com',
    SiteTitle: 'joeplaa.com',
    SiteUrl: process.env.GATSBY_URL,
    TwitterUsername: ``,
    Umami: 'https://umami.joeplaa.com/umami.js',
    WikiDescription: 'How I work and what tools I use.',
    WikiImage: '/images/banner-www-com-white.png',
    WikiTitle: 'Wiki'
}
export const navigation = {
    about: '/home#About',
    blog: process.env.GATSBY_BLOG_URL,
    contact: '/home#Contact',
    home: '/home',
    howto: '/howto',
    howtos: '/howtos',
    portfolio: '/portfolio',
    pricing: '/home#Pricing',
    recommended: process.env.GATSBY_BLOG_URL + '/recommended',
    services: '/home#Services',
    wiki: '/wiki'
}
export const settings = {
    breakpoint: 'md',
    dateFormat: 'LLLL d, yyyy',
    iconSize: '40px'
}
export const urls = {
    email: 'info@joeplaa.com',
    facebook: 'https://www.facebook.com/joeplaadotcom',
    github: 'https://github.com/joeplaa',
    instagram: 'https://www.instagram.com/joeplaa/',
    linkedin: 'https://www.linkedin.com/in/joeplaa/',
    awsCloudfront: 'https://aws.amazon.com/cloudfront/',
    awsLightsail: 'https://aws.amazon.com/lightsail/',
    gatsbyjs: 'https://www.gatsbyjs.com/',
    nextjs: 'https://nextjs.org/',
    wordpress: 'https://wordpress.org/'
}