export const content = {
    '404Header': '404',
    '404Message': "The page you're looking for does not exist (anymore).",
    '404Title': 'Page not found',
    AllRightsReserved: 'All rights reserved.',
    Back: 'Back',
    BacktoPortfolio: 'Back to portfolio',
    Banner: 'Banner',
    Blog: 'Blog',
    Business: 'Business name',
    Copy: 'Copy',
    Email: 'Email',
    EmailErrorMessage: 'Enter a valid email address',
    Filter: 'Filter',
    FilterTags: 'Select tags to show',
    HowtoDisclaimer: 'How-to written and screenshots taken on',
    InterestedIn: "I'm interested in:",
    Loading: 'Loading...',
    MailSendFailed: 'Something went wrong, please try again or email me directly at ',
    MailSendSuccess: "Thank you for sending this message. I'll get back to you as soon as I can.",
    Name: 'Name',
    NameErrorMessage: 'Please enter a name',
    NextPost: 'Next post: ',
    NoOptionsSelect: 'No further tags available',
    Ok: 'Ok',
    PreviousPost: 'Previous post: ',
    PrivacyStatement: 'Privacy Statement',
    SendEmail: 'Send me an email',
    SendEmailDone: 'Thank you for your enquiry',
    ShowAll: 'Show all',
    Submit: 'Submit',
    TermsOfService: 'Terms of service',
    TextBox: 'Questions / other',
    TryAgain: 'Try again',
    WebDesign: 'Website design',
    WebHosting: 'Website hosting',
    WelcomeTo: 'Welcome to'
};
export const metaData = {
    AboutTitle: 'About',
    AuthorName: `Joep van de Laarschot`,
    BusinessName: 'Joeplaa',
    ContactTitle: 'Contact',
    FirstName: 'Joep',
    LastName: 'van de Laarschot',
    HomeDescription: 'Who is Joep and what is Joeplaa?',
    HomeImage: '/images/banner-www-com.png',
    HomeTitle: 'Home',
    HomeSubtitle: 'Website design | Website hosting',
    HowtoDescription: "How-to's and tutorials on subjects like Ubuntu, file-sharing, virtual machines and website hosting.",
    HowtoImage: '/images/banner-www-howto.png',
    HowtoTitle: 'How-to',
    LandingDescription: 'Welcome on joeplaa.com. Click on the links to explore further.',
    LandingTitle: 'Landing',
    PageTitle: 'joeplaa.com',
    PortfolioDescription: 'Examples of my work and skills in front-end development. If like my work, let me know!',
    PortfolioImage: '/images/banner-www-websites.png',
    PortfolioTitle: 'Portfolio',
    PricingDescription: 'If you want a website, here\'s what it costs.',
    PricingTitle: 'Pricing',
    RecommendedDescription: "I've read a lot of books and watched countless videos on the web. Here you can find a list of my recommended books and videos.",
    RecommendedTitle: 'Recommended',
    ServicesDescription: "If you want a website, here's how I can help.",
    ServicesTitle: 'Services',
    SiteDescription: 'Helping people create their digital home.',
    SiteImage: `/images/banner-www-default.png`,
    SiteLanguage: `en-US`,
    SiteLocale: `en_us`,
    SiteName: 'joeplaa.com',
    SiteTitle: 'joeplaa.com',
    SiteUrl: process.env.GATSBY_URL,
    TitleSeparator: '|',
    TitleTemplate: 'joeplaa.com',
    TwitterUsername: '',
    WikiDescription: 'How I work and what tools I use.',
    WikiFaq: 'Faq',
    WikiImage: '/images/banner-www-com.png',
    WikiPricing: 'Pricing',
    WikiProcedure: 'Procedure',
    WikiTitle: 'Wiki'
}
export const navigation = {
    about: '/home#About',
    blog: process.env.GATSBY_BLOG_URL,
    contact: '/home#Contact',
    home: '/home#Banner',
    howto: '/howto',
    portfolio: '/portfolio',
    pricing: '/home#Pricing',
    ps: '/conditions/privacy-statement',
    recommended: process.env.GATSBY_BLOG_URL + '/recommended',
    services: '/home#Services',
    tos: '/conditions/terms-of-service',
    wiki: '/wiki'
}
export const pricing = {
    staticDesign: '€ 750',
    dynamicDesign: '€ 950',
    cmsDesign: '€ 1250',
    customDesign: 'tbd',
    staticHosting: '€ 5',
    dynamicHosting: '€ 10',
    cmsHosting: '€ 15',
    cmsPlusHosting: '€ 20',
    domainHosting: '€ 0.50'
}
export const settings = {
    breakpoint: 'lg',
    iconSize: '40px'
}
export const urls = {
    email: 'info@joeplaa.com',
    facebook: 'https://www.facebook.com/joeplaadotcom',
    github: 'https://github.com/joeplaa',
    instagram: 'https://www.instagram.com/joeplaa/',
    linkedin: 'https://www.linkedin.com/in/joeplaa/',
    umami: 'https://umami.joeplaa.com/umami.js',
    awsCloudfront: 'https://aws.amazon.com/cloudfront/',
    awsLightsail: 'https://aws.amazon.com/lightsail/',
    gatsbyjs: 'https://www.gatsbyjs.com/',
    ghost: 'https://ghost.org/',
    netlifycms: 'https://www.netlifycms.org/',
    nextjs: 'https://nextjs.org/',
    strapi: 'https://strapi.io/',
    wordpress: 'https://wordpress.org/'
}